# es
spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.88.14:9300
      repositories:
        enable: true

# rocketmq
rocketmq:
  name-server: 192.168.88.14:9876
  producer:
    group: search-producer-group
