spring:
  application:
    name: search-application
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:12088
      metric:
        charset: UTF-8
      eager: false

# server
server:
  port: 18086
  servlet:
    context-path: /search-api/

swagger:
  enable: false
