spring:
  boot:
    admin:
      client:
        enabled: false # 暂时不用了
        url: http://127.0.0.1:18097


management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 19083 # 配置独立端口。而该端口，不使用 nginx 对外暴露，从而不配置安全认证。也就是说，内网环境可访问，外网环境不可访问。当然，这么做的前提是，认为内网安全。

swagger:
  enable: true # 暂时不去掉
