spring:
  # datasource
  datasource:
    url: jdbc:mysql://192.168.88.14:3306/mall_product?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ${MALL_MYSQL_PASSWORD}

# rocketmq
rocketmq:
  name-server: 192.168.88.14:9876
  producer:
    group: product-producer-group
