spring:
  application:
    name: user-application
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:12088
      metric:
        charset: UTF-8
      eager: false

# server
server:
  port: 18082
  servlet:
    context-path: /user-api/

swagger:
  enable: false
