spring:
  # datasource
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/youngmall?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: PASSWORD123

# mybatis
mybatis-plus:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.iocoder.mall.pay.biz.dataobject

# dubbo
dubbo:
  application:
    name: pay-service
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: -1
    name: dubbo
  scan:
    base-packages: cn.iocoder.mall.pay.biz.service
  provider:
    filter: -exception
    PayTransactionService:
      version: 1.0.0
    PayRefundService:
      version: 1.0.0

# rocketmq
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: pay-producer-group

# seata
seata:
  tx-service-group: my_test_tx_group
